language: python
cache: pip
dist: xenial

python:
 - "3.6"
 - "3.7"

install:
 - pip install --upgrade black
 - pip install --upgrade flake8
 - pip install --upgrade -r requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff --target-version py36 .

 # Dummy run
 - python random_street_view.py --help

matrix:
  fast_finish: true
